os: linux
lang: cpp
addons:
    - apt
        - sources:
          - ubuntu-toolchain-r-test
        - packages:
          - g++4.9
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libarmadillo-dev
    - sudo apt-get install -qq libgsl-dev

script: make
